### ISSUE TITLE
在真机上运行报错，请问您能帮忙看一下吗？

### ISSUE THREAD

**Issue by Evmilk** [wuzhiming/AndroidInstantCookieDemo#1]
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while calling command (com.google.android.instantapps.sdk.cli.RunCommand@4f787b): com.google.android.instantapps.sdk.lib.AdbHelper$AdbCommandException: Error starting UrlHandler for https://org.cocos2d.instantcookiedemo/game
Command output:
Starting: Intent { act=android.intent.action.VIEW dat=https://org.cocos2d.instantcookiedemo/... cmp=com.google.android.instantapps.supervisor/.UrlHandler }

Error type 3

Error: Activity class {com.google.android.instantapps.supervisor/com.google.android.instantapps.supervisor.UrlHandler} does not exist.

	at picocli.CommandLine.execute(CommandLine.java:837)
	at picocli.CommandLine.access$700(CommandLine.java:111)
	at picocli.CommandLine$RunAll.handleParseResult(CommandLine.java:1024)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1100)
	at picocli.CommandLine.parseWithHandler(CommandLine.java:1053)
	at com.google.android.instantapps.sdk.cli.Main.aia(Main.java:51)
	at com.google.android.instantapps.sdk.cli.Main.main(Main.java:43)
Caused by: com.google.android.instantapps.sdk.lib.AdbHelper$AdbCommandException: Error starting UrlHandler for https://org.cocos2d.instantcookiedemo/game
Command output:
Starting: Intent { act=android.intent.action.VIEW dat=https://org.cocos2d.instantcookiedemo/... cmp=com.google.android.instantapps.supervisor/.UrlHandler }

Error type 3

Error: Activity class {com.google.android.instantapps.supervisor/com.google.android.instantapps.supervisor.UrlHandler} does not exist.

	at com.google.android.instantapps.sdk.lib.AdbHelper.startUrlHandler(AdbHelper.java:461)
	at com.google.android.instantapps.sdk.lib.RunHandlerImpl.doRun(RunHandlerImpl.java:472)
	at com.google.android.instantapps.sdk.lib.RunHandlerImpl.runZip(RunHandlerImpl.java:162)
	at com.google.android.instantapps.sdk.cli.RunCommand.call(RunCommand.java:105)
	at com.google.android.instantapps.sdk.cli.RunCommand.call(RunCommand.java:16)
	at picocli.CommandLine.execute(CommandLine.java:830)
	... 6 more
执行命令出错，返回值：1。

用的是您的项目，然后输出了这个错误

**Comment by wuzhiming** [comment]
可以试试更新下android 到最新的版本

**Comment by Evmilk** [comment]
好了，更新了安卓的版本之后就可以了，非常感谢您啊！
